### ISSUE TITLE
Criar feature dentro de uma ja existente

### ISSUE THREAD

**Issue by moreirawebmaster** [ricardoemerson/create-flutter-widgets-and-classes#1]
Olá tudo bem?

Estou com um bug na ultima versão lançada que ao criar um Feature GetX dentro de um existente, ele cria a nova pasta e os arquivos vazios.

Exemplo:

auth
  > login
     > login_binding.dart
     > login_controller.dart
     > login_page.dart
     
os arquivos mencionados acima ficam todos vazios. Fora o fato da routes que ja existe ficar toda bagunçada.

Obrigado.

**Comment by ricardoemerson** [comment]
Thiago fiz vários testes durante a alteração da extensão e fiz novos testes agora e comigo não está ocorrendo o problema.

Até subi um vídeo pra você ver como está funcionando https://youtu.be/AhI_3FxJgJ0

Será que você estava com arquivo aberto não salvo e por isso bloqueou a escrita do arquivo?

**Comment by ricardoemerson** [comment]
Thiago acredito que o problema tenha ocorrido quando você já tinha uma rota definida na versão anterior sem uso de constantes para rotas e quando foi criar uma nova rota anhinhada a extensão não conseguiu capturar as constantes de rotas anteriores por não existirem. Adicionei uma correção para esta situação.

Favor fazer novo teste.

**Comment by moreirawebmaster** [comment]
Vou reabrir e tentar explicar melhor em video.

Segue o vídeo:

https://user-images.githubusercontent.com/1142139/173074339-f2a02987-ac91-48f1-8bf1-6a6aec64c714.mp4

https://user-images.githubusercontent.com/1142139/173075771-6e240a55-ee1d-4acc-929b-8adeb2f80be0.mp4

@ricardoemerson

**Comment by ricardoemerson** [comment]
@moreirawebmaster pode ser alguma particularidade do seu projeto.

Faz o seguinte, sobe ele pro github e me envia o link do repositório para que eu possa baixar aqui e fazer testes e verificar quais erros podem estar ocorrendo.
