### ISSUE TITLE
Empty generated files 

### ISSUE THREAD

**Issue by Kemorave** [ricardoemerson/create-flutter-widgets-and-classes#2]
Hello and thank you for this awesome extension i just started learning flutter and it helped me a lot.
after updating visual code (VSCode x64-1.69.2) and all of my extensions along with it, now every time i try to generate an app structure or a module or any other command i get 3 to 2 to 1 empty files per attempt (randomly) and sometimes none 

![Screenshot (4)](https://user-images.githubusercontent.com/68113092/180638637-bbf44857-79fb-4133-9827-fe603ea416cd.png)

![Screenshot (9)](https://user-images.githubusercontent.com/68113092/180638828-ccd89bee-e5b7-4240-ab93-0eadcd206661.png)

![Screenshot (10)](https://user-images.githubusercontent.com/68113092/180638902-32b1c2ee-cbbc-4c5e-a362-4195c430e549.png)

![Screenshot (11)](https://user-images.githubusercontent.com/68113092/180638951-437153d4-081c-4596-96f9-a6d5641761f9.png)

Thanks for your time and please forgive my grammar mistakes EN is not my native language

**Comment by Kemorave** [comment]
Rolling back VS code to version `1.65.2` fixed it for me

**Comment by ricardoemerson** [comment]
Hi @Kemorave. That's weird!

![vscode-flutter-tools](https://user-images.githubusercontent.com/2879795/181277151-2d6548bf-81c0-421d-b432-9202cc205434.gif)

I am using vscode in version 1.69.2 and the extension it is working fine for me.

**Comment by ricardoemerson** [comment]
Do the following:

![vscode-flutter-tools-2](https://user-images.githubusercontent.com/2879795/181280174-8750bcf3-1a6f-4b75-9303-9263ae9d1d75.gif)

Let's see what's going on with your.

**Comment by Kemorave** [comment]
> Do the following:
> 
> ![vscode-flutter-tools-2](https://user-images.githubusercontent.com/2879795/181280174-8750bcf3-1a6f-4b75-9303-9263ae9d1d75.gif)
> 
> Let's see what's going on with your.

Thanks for replying its a really weird issue indeed, i just updated vscode to `version 1.69.2` and followed your steps see the screenshot bellow

![image](https://user-images.githubusercontent.com/68113092/181305603-fcf77b88-050f-42ab-99a9-ab29429859e1.png)

On the first time everything work but When this error is thrown the extension just keeps making blank files afterwards and never recover until next reload

**Comment by ricardoemerson** [comment]
@Kemorave, I tried to simulate here the same path of folders that you are using in your project and here the problem does not occur.

Looking at the image you sent me earlier, why is your lib folder showing up twice in VSCode. I believe the problem may be there.

Have to see if you have any other extension that could be causing the error.


![image](https://user-images.githubusercontent.com/2879795/181763507-a80743ec-a72a-46ed-83f6-adadea5921ad.png)

**Comment by Kemorave** [comment]
> 
> @Kemorave, I tried to simulate here the same path of folders that you are using in your project and here the problem does not occur.
> 
> Looking at the image you sent me earlier, why is your lib folder showing up twice in VSCode. I believe the problem may be there.
> 
> Have to see if you have any other extension that could be causing the error.
> 
> 
> ![image](https://user-images.githubusercontent.com/2879795/181763507-a80743ec-a72a-46ed-83f6-adadea5921ad.png)
> 

I actually made that folder from previous attempts to solve the problem (I suspected the path issues too so I moved/created projects in different paths and played around for trial purposes), sorry for the confusion I should have deleted it before taking the screenshot. 
I also already tried removing all my other extensions and deleting the vscode settings and cache folders but **nothing** worked for me except rolling vscode back to the old version I used to work with.
at this point I really believe its a weird bug in vscode and something gets broken after update.
