### ISSUE TITLE
Plugin Not Updated in Visual Studio Code Extensions Marketplace

### ISSUE THREAD

**Issue by Pevalcar** [ricardoemerson/create-flutter-widgets-and-classes#4]
I am reporting an issue regarding the availability of the plugin in the Visual Studio Code Extensions Marketplace. It appears that the plugin has not been updated to the latest version in the marketplace.

**Comment by ricardoemerson** [comment]
Certainly, I am currently in the process of finalizing the update of the extension's documentation so that I can proceed with updating it on the marketplace.
